### ISSUE TITLE
Failing travis build

### ISSUE THREAD

**Issue by alexgorbatchev** [alexgorbatchev/node-browser-builtins#49]
@AndreasMadsen out build is failing all of a sudden... do you know if something broke from under us?

![travis ci - free hosted continuous integration platform for the open source community 2015-01-13 14-34-09](https://cloud.githubusercontent.com/assets/65633/5730689/58807f22-9b31-11e4-9136-f436ff63d393.png)

**Comment by AndreasMadsen** [comment]
Looks like the travis have cleared the sauce lab token, or many zuul have changed the required token name. It should be easily fixed by using following the link.

**Comment by AndreasMadsen** [comment]
fixed. As suspected someting was wrong with the travis env.

**Comment by alexgorbatchev** [comment]
Thanks!
