### ISSUE TITLE
`process` should resolve to browser.js instead of index.js

### ISSUE THREAD

**Issue by andersekdahl** [alexgorbatchev/node-browser-builtins#50]
Currently `process` is resolved with `"process": require.resolve('process/')` but the `process` package has one entry point for Node and one for browser. By using `require.resolve('process/')` you get the Node entry point, which doesn't work for the browser. The same fix should be applied to `process` that is applied to `os-browserify`.

That is, this line:
```
"process": require.resolve('process/'),
```

Should be:
```
"process": path.resolve(require.resolve('process/'), '..', 'browser.js'),
```

**Comment by AndreasMadsen** [comment]
Good catch. Mind doing a PR?

**Comment by andersekdahl** [comment]
I'm on it!
