### ISSUE TITLE
events.js is missing

### ISSUE THREAD

**Issue by fresheneesz** [alexgorbatchev/node-browser-builtins#56]

**Comment by AndreasMadsen** [comment]
It is a 3rd party module: https://github.com/alexgorbatchev/node-browser-builtins/blob/master/index.js#L25

**Comment by fresheneesz** [comment]
@AndreasMadsen The docs still say that it should be at that path:

```
events: '/user/node_modules/browser-builtins/builtin/events.js',
```

**Comment by AndreasMadsen** [comment]
Okay, can you make a pull request.

**Comment by fresheneesz** [comment]
Unfortunately, since I don't use this module directly (only through things like webpack), I don't know what would be appropriate to change the readme to.
